version: '3.6'
services:
  app:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .devcontainer/.env
    ports: 
      - "8080:8080"
    volumes:
      - .:/workspace:cached
      
    # Starts up the go application automatically
    command: go run app.go

  postgres:
    image: mdillon/postgis:11
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testingwithrentals
    ports:
      - "5434:5432"
    volumes:
      - ./sql-init.sql:/docker-entrypoint-initdb.d/sql-init.sql
